// ============================================================
// BLACH GALLERY â€” CATALOGUE COMPLET
// ImportÃ© depuis artofBLACH (Etsy)
// Source de vÃ©ritÃ© unique.
// ============================================================

export const ARTISTS = {
  blach: {
    id: 'blach',
    name: 'Maxime BlachÃ¨re',
    alias: 'BLACHÂ®',
    bio: 'Artiste lyonnais nÃ© en 1980, fondateur du collectif BLACH Gallery.',
    coefficient: 1200,
  },
  carotte: { id: 'carotte', name: 'La Carotte', alias: 'Carotte', coefficient: 600 },
}

export const CATEGORIES = [
  { id: 'original', label: 'Originaux', icon: '*' },
  { id: 'editions-limitees', label: 'Ã‰ditions LimitÃ©es', icon: 'â–' },
  { id: 'new-york', label: 'New York', icon: 'ðŸ—½' },
  { id: 'paris', label: 'Paris', icon: 'ðŸ—´' },
  { id: 'france', label: 'France', icon: 'ðŸ‡«ðŸ‡·' },
  { id: 'europe', label: 'Europe', icon: 'ðŸ°' },
  { id: 'asia', label: 'Asie', icon: 'ðŸ¯' },
  { id: 'animal-fruit', label: 'Animal / Fruit', icon: 'ðŸ¾' },
  { id: 'iceberg', label: 'Iceberg', icon: 'ðŸŒŠ' },
  { id: 'graffiti-name', label: 'Graffiti Name', icon: 'âœï¸' },
]

export const ARTWORKS = [
  {
    id: 'new-york-junior', slug: 'new-york-junior',
    title: 'New York Junior', artist: 'blach', year: 2023, serie: 'Fluxus 2.0',
    technique: 'Impression Offset', support: 'toile 500g',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'junior', 'graffiti', 'fluxus'],
    description: "New York Junior — Impression Offset 75x50 cm. Édition limitée /30 signée et numérotée. Certificat d'authenticité BLACH®.",
    images: ['/images/new-york-junior.jpg', '/images/new-york-junior-2.jpg', '/images/new-york-junior-3.jpg', '/images/new-york-junior-4.jpg', '/images/new-york-junior-5.jpg', '/images/new-york-junior-6.jpg', '/images/new-york-junior-7.jpg', '/images/new-york-junior-8.jpg', '/images/new-york-junior-9.jpg', '/images/new-york-junior-10.jpg', '/images/new-york-junior-11.jpg', '/images/new-york-junior-12.jpg'],
  },
  {
    id: 'new-york-bored-ape-fluo', slug: 'new-york-bored-ape-fluo',
    title: "New York Bored Ape Fluo", titleEn: "New York Bored Ape Fluo",
    description: "VIC New York Bored Ape Fluo â€” GiclÃ©e sur Dibond aluminium brillant 60Ã—40 cm. Ã‰dition /30 signÃ©e et numÃ©rotÃ©e.",
    images: ['/images/new-york-bored-ape-fluo.jpg', '/images/new-york-bored-ape-fluo-2.jpg'],
    price: 300, priceFramed: 0,
    format: "60x40 cm",
    dimensions: { width: 60, height: 40, unit: 'cm' },
    edition: 30,
    technique: "GiclÃ©e sur Dibond aluminium brillant",
    support: "Dibond 0.3 cm",
    category: 'new-york',
    year: 2023,
    artist: 'blach',
    serie: 'VIC',
    tags: ['new york', 'bored ape', 'fluo', 'VIC'],
    stock: 20,
    available: true,
    featured: true,
    new: false,
  },
  {
    id: 'new-york-goldorak-albator', slug: 'new-york-goldorak-albator',
    title: 'New York Goldorak & Albator', artist: 'blach', year: 2023, serie: 'VIC',
    technique: 'GiclÃ©e sur Dibond aluminium brillant', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 300, priceFramed: 0,
    available: true, stock: 15, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'goldorak', 'albator', 'manga', 'VIC'],
    description: 'New York vandalisÃ© par Goldorak et Albator. VIC series, Ã©dition /30 signÃ©e.',
    images: ['/images/new-york-goldorak-albator.jpg', '/images/new-york-goldorak-albator-2.jpg', '/images/new-york-goldorak-albator-3.jpg', '/images/new-york-goldorak-albator-4.jpg', '/images/new-york-goldorak-albator-5.jpg'],
  },
  {
    id: 'new-york-goldoblach-2026-xxl', slug: 'new-york-goldoblach-2026-xxl',
    title: 'New York GoldoBlach 2026 XXL', artist: 'blach', year: 2026,
    technique: 'SÃ©rigraphie', support: 'Papier 300g',
    dimensions: { width: 100, height: 70, unit: 'cm' }, edition: 30, price: 890, priceFramed: 0,
    available: true, stock: 12, category: 'new-york', featured: true, new: true,
    tags: ['new york', 'goldorak', 'XXL', '2026'],
    description: 'Oeuvre monumentale 100x70 cm, tirage /30 numÃ©rotÃ©s et signÃ©s.',
    images: ['/images/new-york-goldorak-albator.jpg'],
  },
  {
    id: 'new-york-simpsons', slug: 'new-york-simpsons',
    title: "VIC New York Simpsons",
    description: "La famille Simpson envahit New York. Dibond brillant 60Ã—40 cm, Ã©dition /30.",
    images: ['/images/new-york-simpsons.jpg', '/images/new-york-simpsons-2.jpg', '/images/new-york-simpsons-3.jpg', '/images/new-york-simpsons-4.jpg', '/images/new-york-simpsons-5.jpg', '/images/new-york-simpsons-6.jpg', '/images/new-york-simpsons-7.jpg', '/images/new-york-simpsons-8.jpg', '/images/new-york-simpsons-9.jpg', '/images/new-york-simpsons-10.jpg', '/images/new-york-simpsons-11.jpg'],
    price: 300, priceFramed: 0,
    format: "60x40 cm",
    dimensions: { width: 60, height: 40, unit: 'cm' },
    edition: 30,
    technique: "GiclÃ©e sur Dibond aluminium brillant",
    support: "Dibond 0.3 cm",
    category: 'new-york',
    year: 2024,
    artist: 'blach',
    serie: 'VIC',
    tags: ['new york', 'simpsons', 'VIC', 'pop culture'],
    stock: 20,
    available: false,
    featured: false,
    new: false,
  },
  {
    id: 'new-york-rainbow-xl', slug: 'new-york-rainbow-xl',
    title: 'New York Rainbow XL', artist: 'blach', year: 2024,
    technique: 'GiclÃ©e sur Dibond aluminium brillant', support: 'Dibond 0.3 cm',
    dimensions: { width: 80, height: 56, unit: 'cm' }, edition: 20, price: 450, priceFramed: 0,
    available: false, stock: 10, category: 'new-york', featured: false, new: false,
    tags: ['new york', 'rainbow', 'XL'],
    description: 'New York Rainbow XL. Dibond 80x56 cm, Ã©dition /20.',
    images: ['/images/new-york-goldorak-albator.jpg'],
  },
  {
    id: 'paris-3024', slug: 'paris-3024',
    title: 'Paris 3024', artist: 'blach', year: 2025, serie: 'VIC',
    technique: 'GiclÃ©e sur Dibond aluminium brillant', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 300, priceFramed: 0,
    available: false, stock: 20, category: 'paris', featured: false, new: false,
    tags: ['paris', 'futur', 'VIC', '3024'],
    description: 'Paris projetÃ© en 3024 â€” univers futuriste et colorÃ©. VIC series /30.',
    images: ['/images/new-york-goldorak-albator.jpg'],
  },
  {
    id: 'paris-je-taime', slug: 'paris-je-taime',
    title: "Paris Je T'Aime", artist: 'blach', year: 2023,
    technique: 'Impression offset', support: 'Toile 500g',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: false, stock: 15, category: 'paris', featured: false, new: false,
    tags: ['paris', 'amour', 'toile'],
    description: "Paris revisitÃ©e par BLACHÂ® â€” dÃ©claration d'amour Ã  la capitale. Toile 500g 75x50 cm, /30.",
    images: ['/images/new-york-goldorak-albator.jpg'],
  },
  {
    id: 'arc-de-triomphe-libertay', slug: 'arc-de-triomphe-libertay',
    title: 'Arc de Triomphe de la Libertay', artist: 'blach', year: 2022,
    technique: 'GiclÃ©e sur toile', support: 'Toile sur chÃ¢ssis bois',
    dimensions: { width: 60, height: 60, unit: 'cm' }, edition: 30, price: 150, priceFramed: 190,
    available: false, stock: 10, category: 'paris', featured: false, new: false,
    tags: ['paris', 'arc de triomphe', 'liberte'],
    description: "Arc de Triomphe revisitÃ©. Toile 60x60 cm. Ã‰dition /30.",
    images: ['/images/new-york-goldorak-albator.jpg'],
  },
  {
    id: 'lyon-fluence', slug: 'lyon-fluence',
    title: "Lyon 1'Fluence XL", artist: 'blach', year: 2023, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 90, height: 60, unit: 'cm' }, edition: 15, price: 220, priceFramed: 250,
    available: true, stock: 10, category: 'france', featured: true, new: false,
    tags: ['lyon', 'fluence', 'XL'],
    description: "Lyon 1'Fluence XL â€” GiclÃ©e Dibond 90x60 cm, Ã©dition /15 signÃ©e.",
    images: ['/images/lyon-fluence.jpg'],
  },
  {
    id: 'lyon-nb', slug: 'lyon-nb',
    title: 'Lyon NB', artist: 'blach', year: 2022, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 100, priceFramed: 130,
    available: true, stock: 10, category: 'france', featured: false, new: false,
    tags: ['lyon', 'noir et blanc'],
    description: "Lyon en noir et blanc. GiclÃ©e Dibond 60x40 cm, Ã©dition /30.",
    images: ['/images/lyon-nb.jpg'],
  },
  {
    id: 'lyon-urc-xl', slug: 'lyon-urc-xl',
    title: 'Lyon URc XL', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 80, height: 60, unit: 'cm' }, edition: 20, price: 190, priceFramed: 230,
    available: true, stock: 10, category: 'france', featured: false, new: false,
    tags: ['lyon', 'urc', 'XL'],
    description: "Lyon URc XL. GiclÃ©e Dibond 80x60 cm, Ã©dition /20.",
    images: ['/images/lyon-urc-xl.jpg'],
  },
  {
    id: 'lyon-guignol-xl', slug: 'lyon-guignol-xl',
    title: 'Lyon Guignol XL', artist: 'blach', year: 2023, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 90, height: 60, unit: 'cm' }, edition: 15, price: 220, priceFramed: 250,
    available: true, stock: 10, category: 'france', featured: true, new: false,
    tags: ['lyon', 'guignol', 'XL'],
    description: "Lyon Guignol XL. GiclÃ©e Dibond 90x60 cm, Ã©dition /15.",
    images: ['/images/lyon-guignol-xl.jpg'],
  },
  {
    id: 'lyon-opera', slug: 'lyon-opera',
    title: "VIC Lyon OpÃ©ra Allstars", artist: 'blach', year: 2023, serie: 'VIC',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 60, unit: 'cm' }, edition: 30, price: 150, priceFramed: 190,
    available: true, stock: 10, category: 'france', featured: false, new: false,
    tags: ['lyon', 'opera', 'VIC'],
    description: "VIC Lyon OpÃ©ra Allstars. GiclÃ©e Dibond 60x60 cm, Ã©dition /30.",
    images: ['/images/lyon-opera.jpg'],
  },
  {
    id: 'passerelle-rouge', slug: 'passerelle-rouge',
    title: 'Lyon Passerelle Rouge', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 80, height: 56, unit: 'cm' }, edition: 20, price: 180, priceFramed: 220,
    available: true, stock: 10, category: 'france', featured: false, new: false,
    tags: ['lyon', 'passerelle', 'rouge'],
    description: "Lyon Passerelle Rouge. GiclÃ©e Dibond 80x56 cm, Ã©dition /20.",
    images: ['/images/passerelle-rouge.jpg'],
  },
  {
    id: 'lyon-affiche-vintage', slug: 'lyon-affiche-vintage',
    title: 'Lyon Vintage du Futur', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'GiclÃ©e sur Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'france', featured: false, new: false,
    tags: ['lyon', 'vintage', 'affiche'],
    description: "Lyon Vintage du Futur. GiclÃ©e Dibond 75x50 cm, Ã©dition /30.",
    images: ['/images/lyon-affiche-vintage.jpg'],
  },
  {
    id: 'urc-lyon-xxl-2026', slug: 'urc-lyon-xxl-2026',
    title: 'URC Lyon XXL 2026', artist: 'blach', year: 2026, serie: 'Fluxus',
    technique: 'Mixed media: Acrylique, markers, crayons pastel, fixatif. Vernis satin spray.',
    support: 'Toile 450g/m2',
    dimensions: { width: 120, height: 120, unit: 'cm' }, edition: 1, price: 1500, priceFramed: 1500,
    available: true, stock: 1, category: 'original', featured: true, new: true,
    tags: ['lyon', 'XXL', 'original', 'fluxus', 'cityscape'],
    description: "Oeuvre originale unique 120x120 cm. Techniques mixtes sur toile. Style Fluxus, ville de Lyon.",
    images: ['/images/urc-lyon-xxl-2026.jpg', '/images/urc-lyon-xxl-2026-2.jpg', '/images/urc-lyon-xxl-2026-3.jpg', '/images/urc-lyon-xxl-2026-4.jpg', '/images/urc-lyon-xxl-2026-5.jpg', '/images/urc-lyon-xxl-2026-6.jpg', '/images/urc-lyon-xxl-2026-7.jpg', '/images/urc-lyon-xxl-2026-8.jpg', '/images/urc-lyon-xxl-2026-9.jpg', '/images/urc-lyon-xxl-2026-10.jpg', '/images/urc-lyon-xxl-2026-11.jpg'],
  },
  {
    id: 'new-york-afro-graffiti', slug: 'new-york-afro-graffiti',
    title: 'New York Afro Graffiti', artist: 'blach', year: 2022, serie: 'Fluxus 2.0',
    technique: 'GiclÃ©e sur toile', support: 'Toile 610g',
    dimensions: { width: 80, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'afro', 'graffiti', 'fluxus'],
    description: "New York Afro Graffiti â€” GiclÃ©e sur toile 610g, 80x50 cm. Ã‰dition limitÃ©e /30 signÃ©e et numÃ©rotÃ©e. Certificat d'authenticitÃ© BLACHÂ®.",
    images: ['/images/new-york-afro-graffiti.jpg', '/images/new-york-afro-graffiti-2.jpg', '/images/new-york-afro-graffiti-3.jpg', '/images/new-york-afro-graffiti-4.jpg', '/images/new-york-afro-graffiti-5.jpg', '/images/new-york-afro-graffiti-6.jpg', '/images/new-york-afro-graffiti-7.jpg', '/images/new-york-afro-graffiti-8.jpg', '/images/new-york-afro-graffiti-9.jpg', '/images/new-york-afro-graffiti-10.jpg', '/images/new-york-afro-graffiti-11.jpg'],
  },
  {
    id: 'new-york-bat-blach', slug: 'new-york-bat-blach',
    title: 'VIC Bat Blach', artist: 'blach', year: 2021, serie: 'Fluxus 2.0',
    technique: 'GiclÃ©e sur aluminium Dibond', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 250, priceFramed: 0,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'batman', 'VIC', 'fluxus', 'superheros'],
    description: "VIC Bat Blach â€” Batman s'invite Ã  New York. GiclÃ©e sur Dibond aluminium brillant 60x40 cm. Ã‰dition limitÃ©e /30 signÃ©e et numÃ©rotÃ©e. Certificat d'authenticitÃ© BLACHÂ®.",
    images: ['/images/new-york-bat-blach.jpg', '/images/new-york-bat-blach-2.jpg', '/images/new-york-bat-blach-3.jpg', '/images/new-york-bat-blach-4.jpg', '/images/new-york-bat-blach-5.jpg', '/images/new-york-bat-blach-6.jpg', '/images/new-york-bat-blach-7.jpg', '/images/new-york-bat-blach-8.jpg', '/images/new-york-bat-blach-9.jpg'],
  },
  {
    id: 'new-york-burns-joker-blachcoin', slug: 'new-york-burns-joker-blachcoin',
    title: 'VIC New York Burns vs Joker vs Blachcoin', artist: 'blach', year: 2021, serie: 'Fluxus 2.0',
    technique: 'GiclÃ©e sur toile', support: 'Toile 500g/m2',
    dimensions: { width: 70, height: 102, unit: 'cm' }, edition: 30, price: 250, priceFramed: 0,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'burns', 'joker', 'blachcoin', 'VIC', 'fluxus'],
    description: "VIC New York Burns vs Joker vs Blachcoin â€” Format vertical XXL 70x102 cm. GiclÃ©e sur toile 500g/m2. Ã‰dition limitÃ©e /30 signÃ©e et numÃ©rotÃ©e. Certificat d'authenticitÃ© BLACHÂ®.",
    images: ['/images/new-york-burns-joker-blachcoin.jpg', '/images/new-york-burns-joker-blachcoin-2.jpg', '/images/new-york-burns-joker-blachcoin-3.jpg', '/images/new-york-burns-joker-blachcoin-4.jpg', '/images/new-york-burns-joker-blachcoin-5.jpg', '/images/new-york-burns-joker-blachcoin-6.jpg'],
  },
  {
    id: 'dbz-dragon-ball-z', slug: 'dbz-dragon-ball-z',
    title: 'Dragon Ball Z', artist: 'blach', year: 2023, serie: 'Fluxus 2.0',
    technique: 'GiclÃ©e sur papier', support: 'Papier 300g',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 200, priceFramed: 0,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['dragon ball', 'DBZ', 'manga', 'anime', 'graffiti', 'fluxus'],
    description: "Dragon Ball Z x BLACHÂ® â€” Le dragon lÃ©gendaire s'invite dans l'univers Fluxus. GiclÃ©e sur papier 300g, 75x50 cm. Ã‰dition limitÃ©e /30 signÃ©e et numÃ©rotÃ©e Ã  la main.",
    images: ['/images/dbz-dragon-ball-z.jpg', '/images/dbz-dragon-ball-z-2.jpg', '/images/dbz-dragon-ball-z-3.jpg', '/images/dbz-dragon-ball-z-4.jpg', '/images/dbz-dragon-ball-z-5.jpg', '/images/dbz-dragon-ball-z-6.jpg', '/images/dbz-dragon-ball-z-7.jpg', '/images/dbz-dragon-ball-z-8.jpg', '/images/dbz-dragon-ball-z-9.jpg', '/images/dbz-dragon-ball-z-10.jpg', '/images/dbz-dragon-ball-z-11.jpg'],
  },
  {
    id: 'vic-done-kind', slug: 'vic-done-kind',
    title: 'VIC Done Kind', artist: 'blach', year: 2021, serie: 'ALT0174',
    technique: 'GiclÃ©e sur Aluminium Dibond finition brillante', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 250, priceFramed: 0,
    available: true, stock: 10, category: 'new-york', featured: true, new: false,
    tags: ['new york', 'done', 'kind', 'VIC', 'graffiti', 'fluxus'],
    description: "VIC Done Kind â€” New York vandalisÃ© par les maÃ®tres du graffiti Done et Kind. giclÃ©e. Ã‰dition limitÃ©e /30 signÃ©e et numÃ©rotÃ©e. Certificat d'authenticitÃ© BLACHÂ®.",
    images: ['/images/vic-done-kind.jpg', '/images/vic-done-kind-2.jpg', '/images/vic-done-kind-3.jpg', '/images/vic-done-kind-4.jpg', '/images/vic-done-kind-5.jpg', '/images/vic-done-kind-6.jpg', '/images/vic-done-kind-7.jpg', '/images/vic-done-kind-8.jpg'],
  },
  {
    id: 'vic-new-york-looney-toons', slug: 'vic-new-york-looney-toons',
    title: 'VIC New York Looney Toons', artist: 'blach', year: 2024, serie: 'VIC',
    technique: 'Giclée sur Aluminium Dibond finition brillante', support: 'Dibond 0.3 cm',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 250, priceFramed: 0,
    available: true, stock: 10, category: 'new-york', featured: true, new: true,
    tags: ['new york', 'looney toons', 'bugs bunny', 'road runner', 'VIC', 'graffiti', 'fluxus'],
    description: "VIC New York Looney Toons — Times Square revisitée par BLACH® avec l'univers Looney Toons. Giclée sur Aluminium Dibond finition brillante 60x40 cm. Édition limitée /30 signée et numérotée. Certificat d'authenticité BLACH®.",
    images: ['/images/new-york-looney-toons.jpg', '/images/new-york-looney-toons-2.jpg', '/images/new-york-looney-toons-3.jpg', '/images/new-york-looney-toons-4.jpg', '/images/new-york-looney-toons-5.jpg', '/images/new-york-looney-toons-6.jpg', '/images/new-york-looney-toons-7.jpg', '/images/new-york-looney-toons-8.jpg', '/images/new-york-looney-toons-9.jpg', '/images/new-york-looney-toons-10.jpg'],
  },
  {
    id: 'paris-manege-tour-eiffel-vintage', slug: 'paris-manege-tour-eiffel-vintage',
    title: 'Paris le manège et la tour Eiffel Vintage XL', artist: 'blach', year: 2024, serie: 'VIC',
    technique: 'Giclée vintage sur toile', support: 'Toile 450g/m²',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'paris', featured: true, new: false,
    tags: ['paris', 'tour eiffel', 'manege', 'vintage', 'VIC'],
    description: "Nouvelle estampe grand format de BLACH®. Effet vintage où la Tour Eiffel et un carrousel parisien sont sublimés par des graffitis en noir et blanc, regorgeant de détails et de \"Blacheries\". Un hommage audacieux et poétique à la Ville Lumière. Toile 450g/m², 75x50 cm. Édition limitée /30 signée et numérotée. Certificat d'authenticité BLACH®.",
    images: ['/images/paris-manege-tour-eiffel-vintage.jpg', '/images/paris-manege-tour-eiffel-vintage-2.jpg'],
  },
  {
    id: 'paris-carre-bleu', slug: 'paris-carre-bleu',
    title: 'Paris Carré Bleu édition prestige XL', artist: 'blach', year: 2025, serie: 'VIC',
    technique: 'Giclée sur toile', support: 'Toile 450g/m²',
    dimensions: { width: 60, height: 60, unit: 'cm' }, edition: 30, price: 150, priceFramed: 190,
    available: true, stock: 10, category: 'paris', featured: true, new: false,
    tags: ['paris', 'carre bleu', 'VIC', 'prestige'],
    description: "\"Paris carré bleu\" — édition de prestige 60x60 cm ornée de centaines de graffitis vibrants et de la majestueuse architecture parisienne (Tour Eiffel, Seine, pont). Une œuvre qui célèbre la couleur et le street art à travers une explosion visuelle unique. Série VIC (Vandal Is Color). Toile 450g/m². Certificat d'authenticité signé à la main par l'artiste.",
    images: ['/images/paris-carre-bleu.jpg'],
  },
  {
    id: 'paris-le-louvre', slug: 'paris-le-louvre',
    title: "Paris Le Louvre",
    description: "Le Louvre graffité et vandalisé par BLACH, qui s'attaque ici à la célèbre pyramide et au musée du Louvre. Version nocturne où les couleurs vives et éclatantes des graffitis illuminent la scène, créant un contraste saisissant avec le cadre historique. Format atypique 60x30 cm + marges. Toile haut de gamme 450g. Édition limitée /30 numérotée à la main. ",
    images: ['/images/paris-le-louvre.jpg', '/images/paris-le-louvre-2.jpg', '/images/paris-le-louvre-3.jpg', '/images/paris-le-louvre-4.jpg', '/images/paris-le-louvre-5.jpg', '/images/paris-le-louvre-6.jpg'],
    price: 200, priceFramed: 0,
    format: "60x30 cm",
    dimensions: { width: 60, height: 30, unit: 'cm' },
    edition: 30,
    technique: "Giclée sur toile",
    support: "Toile haut de gamme 450g",
    category: 'paris',
    year: 2024,
    artist: 'blach',
    serie: 'VIC',
    tags: ['paris', 'louvre', 'pyramide', 'VIC', 'nocturne'],
    stock: 10,
    available: true,
    featured: false,
    new: false,
  },
  {
    id: 'paris-place-etoile', slug: 'paris-place-etoile',
    title: "Paris place de l'Etoile", artist: 'blach', year: 2024, serie: 'VIC',
    technique: 'Giclée sur toile', support: 'Toile ultra-résistante 450g/m²',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 100, priceFramed: 0,
    available: true, stock: 10, category: 'paris', featured: false, new: false,
    tags: ['paris', 'arc de triomphe', 'etoile', 'VIC', 'JO 2024'],
    description: "Paris et l'Arc de Triomphe envahis par les graffitis : BLACH réinvente la cérémonie d'ouverture des Jeux Olympiques 2024. Vue aérienne du quartier de l'Étoile et des Champs-Élysées, parsemée de personnages pop et de tags colorés. Toile ultra-résistante 450g/m², 60x40 cm + 10cm de marge blanche. Signée et numérotée à la main.",
    images: ['/images/paris-place-etoile.jpg', '/images/paris-place-etoile-2.jpg'],
  },
  {
    id: 'paris-panoramique-nb-prestige', slug: 'paris-panoramique-nb-prestige',
    title: 'Paris Panoramique noir et blanc édition prestige XL', artist: 'blach', year: 2025, serie: 'VIC',
    technique: 'Lithographie sur toile', support: 'Toile haut de gamme ultra-résistante 450g/m²',
    dimensions: { width: 90, height: 60, unit: 'cm' }, edition: 30, price: 220, priceFramed: 250,
    available: true, stock: 10, category: 'paris', featured: true, new: false,
    tags: ['paris', 'panoramique', 'noir et blanc', 'prestige', 'VIC'],
    description: "Paris Panoramique XL — Lithographie Édition Prestige. Une vision unique de Paris où l'élégance intemporelle du noir et blanc se mêle à l'énergie colorée du street art. Œuvre monumentale (90x60 cm + marges) mettant en scène la Tour Eiffel et les toits parisiens dans une explosion de graffitis vifs et colorés. Toile haut de gamme 450g/m². Certificat d'authenticité signé à la main.",
    images: ['/images/paris-panoramique-nb-prestige.jpg'],
  },
  {
    id: 'paris-reflexion', slug: 'paris-reflexion',
    title: 'Paris Réflexion', artist: 'blach', year: 2025, serie: 'VIC',
    technique: 'Giclée sur toile satinée', support: 'Toile ultra-résistante 450g/m²',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'paris', featured: true, new: true,
    tags: ['paris', 'tour eiffel', 'reflet', 'VIC', 'street art'],
    description: "Découvrez la poésie colorée de BLACH avec cette édition grand format de \"Reflets de Paris\". La Tour Eiffel stylisée se reflète symétriquement dans l'eau, parsemée de détails cachés à explorer : un McDonald's camouflé, un Invader discret, des clins d'œil aux légendes du street art... Une concentration de \"Blacheries\" à redécouvrir à chaque regard. Toile ultra-résistante 450g/m², finition satinée, 75x50 cm + 10cm de marge.",
    images: ['/images/paris-reflexion.jpg'],
  },
  {
    id: 'paris-3024-xl', slug: 'paris-3024-xl',
    title: 'Paris 3024 XL', artist: 'blach', year: 2024, serie: 'VIC',
    technique: 'Giclée', support: 'Toile 450g/m²',
    dimensions: { width: 80, height: 80, unit: 'cm' }, edition: 30, price: 260, priceFramed: 300,
    available: true, stock: 10, category: 'paris', featured: true, new: false,
    tags: ['paris', '3024', 'XL'],
    description: "Paris 3024 XL — 80x80cm prestige.",
    images: ['/images/paris-3024-xl.jpg']
  },
  {
    id: 'paris-je-taime', slug: 'paris-je-taime',
    title: 'Paris Je t\'aime', artist: 'blach', year: 2023, serie: 'VIC',
    technique: 'Giclée', support: 'Toile 450g/m²',
    dimensions: { width: 60, height: 40, unit: 'cm' }, edition: 30, price: 100, priceFramed: 130,
    available: true, stock: 10, category: 'paris', featured: false, new: false,
    tags: ['paris', 'amour'],
    description: "Paris Je t'aime.",
    images: ['/images/paris-je-taime.jpg']
  },
  {
    id: 'arc-de-triomphe-libertay', slug: 'arc-de-triomphe-libertay',
    title: 'Arc de Triomphe liberté soir', artist: 'blach', year: 2024, serie: 'VIC',
    technique: 'Giclée', support: 'Toile 450g/m²',
    dimensions: { width: 80, height: 61, unit: 'cm' }, edition: 30, price: 180, priceFramed: 220,
    available: true, stock: 10, category: 'paris', featured: true, new: false,
    tags: ['paris', 'arc'],
    description: "Arc de Triomphe.",
    images: ['/images/arc-de-triomphe-libertay.jpg']
  },
  {
    id: 'lyon-fluence', slug: 'lyon-fluence',
    title: 'Lyon Fluence', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'Impression', support: 'Toile 450g/m²',
    dimensions: { width: 75, height: 50, unit: 'cm' }, edition: 30, price: 160, priceFramed: 200,
    available: true, stock: 10, category: 'lyon', featured: false, new: false,
    tags: ['lyon'],
    description: "Lyon Fluence.",
    images: ['/images/lyon-fluence.jpg']
  },
  {
    id: 'lyon-nb', slug: 'lyon-nb',
    title: 'Lyon NB', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'Lithographie', support: 'Toile 450g/m²',
    dimensions: { width: 60, height: 80, unit: 'cm' }, edition: 30, price: 190, priceFramed: 230,
    available: true, stock: 10, category: 'lyon', featured: false, new: false,
    tags: ['lyon', 'nb'],
    description: "Lyon NB.",
    images: ['/images/lyon-nb.jpg']
  },
  {
    id: 'lyon-guignol-xl', slug: 'lyon-guignol-xl',
    title: 'Lyon Guignol XL', artist: 'blach', year: 2024, serie: 'Lyon',
    technique: 'Giclée', support: 'Toile 450g/m²',
    dimensions: { width: 80, height: 80, unit: 'cm' }, edition: 30, price: 260, priceFramed: 300,
    available: true, stock: 10, category: 'lyon', featured: true, new: true,
    tags: ['lyon', 'guignol'],
    description: "Lyon Guignol XL.",
    images: ['/images/lyon-guignol-xl.jpg'],
  }]

export function getArtwork(slug) { return ARTWORKS.find(a => a.slug === slug) || null }
export function getFeatured() { return ARTWORKS.filter(a => a.featured) }
export function getNew() { return ARTWORKS.filter(a => a.new) }
export function getArtworksByCategory(cat) { return ARTWORKS.filter(a => a.category === cat) }
export function getArtworksByArtist(id) { return ARTWORKS.filter(a => a.artist === id || a.artist2 === id) }
export function searchArtworks({ query='', artist='', category='', maxPrice=9999, available=false, sort='featured' }={}) {
  let r = [...ARTWORKS]
  if (query) { const q=query.toLowerCase(); r=r.filter(a=>a.title.toLowerCase().includes(q)||a.tags?.some(t=>t.includes(q))) }
  if (artist) r=r.filter(a=>a.artist===artist||a.artist2===artist)
  if (category) r=r.filter(a=>a.category===category)
  if (available) r=r.filter(a=>a.available)
  r=r.filter(a=>a.price<=maxPrice)
  if (sort==='price-asc') r.sort((a,b)=>a.price-b.price)
  else if (sort==='price-desc') r.sort((a,b)=>b.price-a.price)
  else if (sort==='new') r.sort((a,b)=>(b.new?1:0)-(a.new?1:0))
  else r.sort((a,b)=>(b.featured?1:0)-(a.featured?1:0))
  return r
}

