// ============================================================
// BLACH GALLERY — CATALOGUE DES ŒUVRES
// Source de vérité unique. Ajouter les œuvres ici uniquement.
// ============================================================

export const ARTISTS = {
  blach: {
    id: 'blach',
    name: 'Maxime Blachère',
    alias: 'BLACH®',
    bio: 'Artiste lyonnais, fondateur du collectif BLACH Gallery. Son œuvre mêle street art, graffiti et éditions limitées.',
    bio_en: 'Lyon-based artist, founder of the BLACH Gallery collective. His work blends street art, graffiti and limited editions.',
    coefficient: 1200, // €/m²
    instagram: 'https://www.instagram.com/blachgallery',
  },
  carotte: {
    id: 'carotte',
    name: 'La Carotte',
    alias: 'Carotte',
    bio: 'Artiste du collectif BLACH Gallery, univers graphique coloré et urbain.',
    bio_en: 'BLACH Gallery collective artist, colorful and urban graphic universe.',
    coefficient: 600,
  },
}

export const ARTWORKS = [
  {
    id: 'new-york-goldoblach-2026-xxl',
    slug: 'new-york-goldoblach-2026-xxl',
    title: 'New York GoldoBlach 2026 XXL',
    title_en: 'New York GoldoBlach 2026 XXL',
    artist: 'blach',
    year: 2026,
    technique: 'Sérigraphie',
    technique_en: 'Screen print',
    support: 'Papier 300g',
    support_en: '300g paper',
    dimensions: { width: 100, height: 70, unit: 'cm' },
    edition: 30,
    price: 890,
    available: true,
    stock: 12,
    category: 'editions-limitees',
    style: 'Street Art / Pop',
    colors: ['#c8920a', '#1a1a2e', '#e8d5a3'],
    tags: ['new york', 'goldorak', 'XXL', 'sérigraphie', 'blach'],
    description: "Une œuvre monumentale qui fusionne l'icône japonaise Goldorak avec les skylines new-yorkaises dans un écrin doré. Tirée à 30 exemplaires numérotés et signés.",
    description_en: 'A monumental work fusing the Japanese icon Goldorak with New York City skylines in a golden setting. Edition of 30 numbered and signed prints.',
    images: ['/images/new-york-goldoblach-2026-xxl/main.jpg'],
    featured: true,
    new: true,
  },
  {
    id: 'lyon-feat-carotte-xl',
    slug: 'lyon-feat-carotte-xl',
    title: 'Lyon Feat Carotte XL',
    title_en: 'Lyon Feat Carotte XL',
    artist: 'blach',
    artist2: 'carotte',
    year: 2024,
    technique: 'Lithographie offset',
    technique_en: 'Offset lithograph',
    support: 'Papier 250g',
    support_en: '250g paper',
    dimensions: { width: 75, height: 50, unit: 'cm' },
    edition: 30,
    price: 180,
    available: true,
    stock: 18,
    category: 'editions-limitees',
    style: 'Street Art / Collaboration',
    colors: ['#e63946', '#ffd166', '#06d6a0'],
    tags: ['lyon', 'carotte', 'collaboration', 'XL'],
    description: "Collaboration entre BLACH® et Carotte autour de Lyon. Deux univers graphiques qui se rencontrent dans une composition dynamique et colorée.",
    description_en: 'Collaboration between BLACH® and Carotte around the city of Lyon. Two graphic universes meeting in a dynamic, colorful composition.',
    images: ['/images/lyon-feat-carotte-xl/main.jpg'],
    featured: true,
    new: false,
  },
  {
    id: 'lyon-doisneau-feat-carotte',
    slug: 'lyon-doisneau-feat-carotte',
    title: 'Lyon Doisneau Feat Carotte',
    title_en: 'Lyon Doisneau Feat Carotte',
    artist: 'blach',
    artist2: 'carotte',
    year: 2024,
    technique: 'Lithographie offset',
    technique_en: 'Offset lithograph',
    support: 'Toile 500g',
    support_en: '500g canvas',
    dimensions: { width: 48, height: 48, unit: 'cm' },
    edition: 30,
    price: 180,
    available: true,
    stock: 22,
    category: 'editions-limitees',
    style: 'Street Art / Romantique',
    colors: ['#2d3561', '#c84b31', '#ecdbba'],
    tags: ['lyon', 'doisneau', 'carotte', 'square'],
    description: "Hommage à Doisneau revisité par BLACH® et Carotte — la poésie du photographe rencontre l'énergie du street art lyonnais.",
    description_en: "A tribute to Doisneau revisited by BLACH® and Carotte — the photographer's poetry meets the energy of Lyon's street art.",
    images: ['/images/lyon-doisneau-feat-carotte/main.jpg'],
    featured: false,
    new: false,
  },
  {
    id: 'lyon-1fluence-xl',
    slug: 'lyon-1fluence-xl',
    title: "Lyon 1'Fluence XL",
    title_en: "Lyon 1'Fluence XL",
    artist: 'blach',
    year: 2023,
    technique: 'Sérigraphie',
    technique_en: 'Screen print',
    support: 'Papier 300g',
    support_en: '300g paper',
    dimensions: { width: 75, height: 50, unit: 'cm' },
    edition: 15,
    price: 270,
    available: true,
    stock: 7,
    category: 'editions-limitees',
    style: 'Street Art / Typographie',
    colors: ['#ff6b35', '#1b1b2f', '#f7c59f'],
    tags: ['lyon', 'typo', 'sérigraphie', 'rareté'],
    description: "Lyon 1'Fluence — une œuvre typographique sur l'influence de Lyon dans la culture urbaine. Tirage limité à 15 exemplaires numérotés et signés.",
    description_en: "Lyon 1'Fluence — a typographic work on Lyon's influence in urban culture. Limited edition of 15 numbered and signed prints.",
    images: ['/images/lyon-1fluence-xl/main.jpg'],
    featured: false,
    new: false,
  },
  {
    id: 'paris-je-taime',
    slug: 'paris-je-taime',
    title: "Paris Je T'Aime",
    title_en: "Paris Je T'Aime",
    artist: 'blach',
    year: 2023,
    technique: 'Impression offset',
    technique_en: 'Offset print',
    support: 'Toile 500g',
    support_en: '500g canvas',
    dimensions: { width: 75, height: 50, unit: 'cm' },
    edition: 30,
    price: 250,
    available: true,
    stock: 15,
    category: 'editions-limitees',
    style: 'Street Art / Paris',
    colors: ['#003087', '#ef3340', '#ffffff'],
    tags: ['paris', 'amour', 'édition', 'toile'],
    description: "Paris revisitée par BLACH® — une déclaration d'amour à la capitale en édition limitée signée sur toile 500g.",
    description_en: "Paris revisited by BLACH® — a declaration of love to the French capital in a signed limited edition on 500g canvas.",
    images: ['/images/paris-je-taime/main.jpg'],
    featured: true,
    new: false,
  },
]

export const CATEGORIES = [
  { id: 'editions-limitees', label: 'Éditions Limitées', label_en: 'Limited Editions', icon: '🎨' },
  { id: 'originaux', label: 'Originaux', label_en: 'Originals', icon: '✦' },
  { id: 'sculptures', label: 'Sculptures', label_en: 'Sculptures', icon: '🗿' },
  { id: 'street-art', label: 'Street Art', label_en: 'Street Art', icon: '🏙️' },
]

export function getArtwork(slug) {
  return ARTWORKS.find(a => a.slug === slug) || null
}

export function getArtworksByCategory(category) {
  return ARTWORKS.filter(a => a.category === category)
}

export function getFeatured() {
  return ARTWORKS.filter(a => a.featured)
}
